print("Hello World")
print('hello Sakib Khan')
print('I am python, a programming language not snake')
print("Hello Brother\n when you will go home?")
print("Why you \n & me are not coming home 24115.5")